import { getDb, toIso } from "./admin";
import { getLuxesupplyOrg } from "./staff";
import { getQuoteById, linkQuoteToInvoice, finalizeInvoiceRequestAsSold } from "./quotes";
import { findBuyerByIdentifier } from "./buyers";
import { getShippingRules } from "./settings";
import {
  parseShippingComp,
  reevaluateInvoiceShipping,
  type ShippingComp,
} from "@/lib/shipping-rules";
import {
  FIRESTORE_INVOICE_STATUS,
  FULFILLMENT_STATUS,
  INVOICE_TERMS,
  netDaysFromTerms,
  type FulfillmentStatus,
} from "@/lib/constants";

// Formal invoices generated by staff from an approved/processed invoice
// request (`salesPortalQuotes`). Separate collection so the request pipeline
// (open → contacted → quoted) and the invoice/fulfillment lifecycle
// (SENT → PAID, UNFULFILLED → SHIPPED) don't overload one document shape.
export type InvoiceLineItem = {
  sku: string;
  title: string;
  brand: string;
  quantity: number;
  price: number;
  imageUrl: string | null;
};

export type InvoicePayment = {
  amount: number;
  method: string;
  reference: string;
  note: string;
  receivedAt: string | null;
  recordedBy: string;
};

export type PortalInvoice = {
  id: string;
  invoiceNumber: string;
  quoteId: string;
  organizationId: string;
  portalUsername: string;
  buyerDisplayName: string;
  customerName: string;
  customerEmail: string;
  customerCompany: string;
  customerPhone: string;
  items: InvoiceLineItem[];
  itemCount: number;
  subtotal: number;
  shipping: number;
  /** Buyer-chosen method label snapshotted from the order request (may be empty on staff-created orders). */
  shippingLabel: string;
  /** Set when the free-shipping threshold comped shipping on this invoice. */
  shippingComp: ShippingComp | null;
  total: number;
  terms: string;
  /** Multiline Bill To override snapshotted from the buyer account at generation. */
  billTo: string;
  /** Seller's note to the shipper for this order ("fit it all in one box",
   *  "pack extra careful") — shown prominently on the pack station. */
  packingNote: string;
  poNumber: string | null;
  status: string;
  payments: InvoicePayment[];
  /** Sum of recorded payments. */
  amountPaid: number;
  /** total - amountPaid, floored at 0; 0 when status is PAID regardless. */
  balance: number;
  fulfillmentStatus: FulfillmentStatus;
  carrier: string | null;
  trackingNumber: string | null;
  shippedAt: string | null;
  issuedAt: string | null;
  dueDate: string | null;
  paidAt: string | null;
  lastReminderAt: string | null;
  createdAt: string | null;
  updatedAt: string | null;
  createdBy: string;
};

function serializeInvoice(id: string, d: Record<string, unknown>): PortalInvoice {
  const items = Array.isArray(d.items) ? (d.items as Array<Record<string, unknown>>) : [];
  return {
    id,
    invoiceNumber: String(d.invoiceNumber || ""),
    quoteId: String(d.quoteId || ""),
    packingNote: String(d.packingNote || ""),
    organizationId: String(d.organizationId || ""),
    portalUsername: String(d.portalUsername || ""),
    buyerDisplayName: String(d.buyerDisplayName || ""),
    customerName: String(d.customerName || ""),
    customerEmail: String(d.customerEmail || ""),
    customerCompany: String(d.customerCompany || ""),
    customerPhone: String(d.customerPhone || ""),
    items: items.map((i) => ({
      sku: String(i.sku || ""),
      title: String(i.title || ""),
      brand: String(i.brand || ""),
      quantity: Math.max(1, Math.round(Number(i.quantity) || 1)),
      price: Number(i.price) || 0,
      imageUrl: i.imageUrl ? String(i.imageUrl) : null,
    })),
    itemCount: Number(d.itemCount || items.length || 0),
    subtotal: Number(d.subtotal || 0),
    shipping: Number(d.shipping || 0),
    shippingLabel: String(d.shippingLabel || ""),
    shippingComp: parseShippingComp(d.shippingComp),
    total: Number(d.total || 0),
    terms: String(d.terms || INVOICE_TERMS),
    billTo: String(d.billTo || ""),
    poNumber: d.poNumber ? String(d.poNumber) : null,
    status: String(d.status || FIRESTORE_INVOICE_STATUS.SENT),
    ...(() => {
      const payments = (Array.isArray(d.payments) ? (d.payments as Array<Record<string, unknown>>) : []).map(
        (p) => ({
          amount: Number(p.amount) || 0,
          method: String(p.method || "wire"),
          reference: String(p.reference || ""),
          note: String(p.note || ""),
          receivedAt: toIso(p.receivedAt),
          recordedBy: String(p.recordedBy || ""),
        }),
      );
      const amountPaid = payments.reduce((s, p) => s + p.amount, 0);
      const total = Number(d.total || 0);
      const paid = String(d.status || "") === FIRESTORE_INVOICE_STATUS.PAID;
      return { payments, amountPaid, balance: paid ? 0 : Math.max(0, total - amountPaid) };
    })(),
    fulfillmentStatus: (String(d.fulfillmentStatus || FULFILLMENT_STATUS.UNFULFILLED) as FulfillmentStatus),
    carrier: d.carrier ? String(d.carrier) : null,
    trackingNumber: d.trackingNumber ? String(d.trackingNumber) : null,
    shippedAt: toIso(d.shippedAt),
    issuedAt: toIso(d.issuedAt),
    dueDate: toIso(d.dueDate),
    paidAt: toIso(d.paidAt),
    lastReminderAt: toIso(d.lastReminderAt),
    createdAt: toIso(d.createdAt),
    updatedAt: toIso(d.updatedAt),
    createdBy: String(d.createdBy || ""),
  };
}

/** Display status: OVERDUE is computed, never stored, so "mark paid" stays the only status mutation. */
export function displayInvoiceStatus(inv: { status: string; dueDate: string | null }): string {
  if (
    inv.status === FIRESTORE_INVOICE_STATUS.SENT &&
    inv.dueDate &&
    new Date(inv.dueDate).getTime() < Date.now()
  ) {
    return "OVERDUE";
  }
  return inv.status;
}

async function nextInvoiceNumber(orgId: string): Promise<string> {
  const db = getDb();
  const ref = db.collection("organizations").doc(orgId);
  // Prefix comes from Settings → Invoicing; read inside the same transaction
  // snapshot as the sequence so both reflect one consistent org doc.
  let prefix = "INV";
  const seq = await db.runTransaction(async (tx) => {
    const snap = await tx.get(ref);
    const data = (snap.data() || {}) as Record<string, unknown>;
    const salesPortal = (data.salesPortal || {}) as Record<string, unknown>;
    const invoicing = (salesPortal.invoicing || {}) as Record<string, unknown>;
    const configured = String(invoicing.invoicePrefix || "").trim().slice(0, 16).replace(/-+$/, "");
    if (configured) prefix = configured;
    const current = Number(salesPortal.invoiceSeq) || 1000;
    const next = current + 1;
    tx.set(
      ref,
      { salesPortal: { ...salesPortal, invoiceSeq: next }, updatedAt: new Date() },
      { merge: true },
    );
    return next;
  });
  return `${prefix}-${seq}`;
}

/**
 * Staff action: turn a priced invoice request into a formal invoice. Snapshots
 * the request's current line items/total, assigns a sequential invoice
 * number, and links the two documents both ways (invoice.quoteId,
 * quote.invoiceId) so either side can navigate to the other.
 */
export async function createInvoiceFromQuote(
  quoteId: string,
  staffEmail: string,
): Promise<PortalInvoice> {
  const quote = await getQuoteById(quoteId);
  if (!quote) throw new Error("Order request not found.");
  if (quote.invoiceId) throw new Error("This request already has an invoice.");
  if (!quote.items.length) throw new Error("Cannot invoice an empty request.");

  const org = await getLuxesupplyOrg();
  const invoiceNumber = await nextInvoiceNumber(org.id);
  const now = new Date();

  // Per-buyer payment terms (set on the client account / payment tier) drive
  // the invoice terms + due date; org-wide Net-30 is only the fallback for
  // guests or lookup failures.
  let terms: string = INVOICE_TERMS;
  let billTo = "";
  if (quote.portalUsername) {
    try {
      const buyer = await findBuyerByIdentifier(quote.portalUsername);
      if (buyer?.paymentTerms) terms = buyer.paymentTerms;
      if (buyer?.billTo) billTo = buyer.billTo;
    } catch (err) {
      console.warn("[invoices] buyer terms lookup failed:", err instanceof Error ? err.message : err);
    }
  }
  const dueDate = new Date(now.getTime() + netDaysFromTerms(terms) * 24 * 60 * 60 * 1000);

  const items: InvoiceLineItem[] = quote.items.map((i) => ({
    sku: String(i.sku || ""),
    title: String(i.title || ""),
    brand: String(i.brand || ""),
    quantity: Math.max(1, Math.round(Number(i.quantity) || 1)),
    price: Number(i.price) || 0,
    imageUrl: i.imageUrl ? String(i.imageUrl) : null,
  }));
  const subtotal =
    quote.cartTotal != null ? Math.round(quote.cartTotal) : items.reduce((s, i) => s + i.price * i.quantity, 0);
  // Staff may have edited lines since submit, so the free-shipping comp is
  // re-checked in both directions against the invoice subtotal. The buyer's
  // agreed fee is never repriced — qualifying zeroes it, disqualifying
  // restores the fee they saw at checkout.
  const shippingRules = await getShippingRules();
  const { shipping, comp: shippingComp } = reevaluateInvoiceShipping(shippingRules, quote, subtotal);
  const total = subtotal + shipping;

  const ref = getDb().collection("salesPortalInvoices").doc();
  await ref.set({
    invoiceNumber,
    quoteId,
    organizationId: org.id,
    portalUsername: quote.portalUsername,
    buyerDisplayName: quote.buyerDisplayName,
    customerName: quote.customerName,
    customerEmail: quote.customerEmail,
    customerCompany: quote.customerCompany,
    customerPhone: quote.customerPhone,
    items,
    itemCount: items.length,
    subtotal,
    shipping,
    shippingLabel: quote.shippingLabel || "",
    shippingComp,
    total,
    terms,
    billTo,
    poNumber: String(quote.poNumber || "").trim() || null,
    status: FIRESTORE_INVOICE_STATUS.SENT,
    fulfillmentStatus: FULFILLMENT_STATUS.UNFULFILLED,
    carrier: null,
    trackingNumber: null,
    shippedAt: null,
    issuedAt: now,
    dueDate,
    paidAt: null,
    createdAt: now,
    updatedAt: now,
    createdBy: staffEmail,
  });

  await linkQuoteToInvoice(quoteId, { id: ref.id, invoiceNumber });
  await finalizeInvoiceRequestAsSold(quoteId, staffEmail);

  const saved = await ref.get();
  return serializeInvoice(saved.id, saved.data() || {});
}

export async function listInvoices(opts?: { limit?: number }): Promise<PortalInvoice[]> {
  const org = await getLuxesupplyOrg();
  // Ceiling raised from 300 to 1000 so the performance dashboard can pull a full
  // year of invoices; existing callers still pass their own smaller limits.
  const limitCount = Math.min(Math.max(opts?.limit || 100, 1), 1000);
  const db = getDb();

  let snap;
  try {
    snap = await db
      .collection("salesPortalInvoices")
      .where("organizationId", "==", org.id)
      .orderBy("createdAt", "desc")
      .limit(limitCount)
      .get();
  } catch {
    snap = await db
      .collection("salesPortalInvoices")
      .where("organizationId", "==", org.id)
      .limit(limitCount)
      .get();
  }

  return snap.docs
    .map((doc) => serializeInvoice(doc.id, doc.data() || {}))
    .sort((a, b) => String(b.createdAt || "").localeCompare(String(a.createdAt || "")));
}

export async function listInvoicesForBuyer(username: string): Promise<PortalInvoice[]> {
  if (!username) return [];
  const org = await getLuxesupplyOrg();
  const db = getDb();

  let snap;
  try {
    snap = await db
      .collection("salesPortalInvoices")
      .where("organizationId", "==", org.id)
      .where("portalUsername", "==", username)
      .orderBy("createdAt", "desc")
      .limit(100)
      .get();
  } catch {
    snap = await db
      .collection("salesPortalInvoices")
      .where("organizationId", "==", org.id)
      .where("portalUsername", "==", username)
      .limit(100)
      .get();
  }

  return snap.docs
    .map((doc) => serializeInvoice(doc.id, doc.data() || {}))
    .sort((a, b) => String(b.createdAt || "").localeCompare(String(a.createdAt || "")));
}

export async function getInvoiceById(id: string): Promise<PortalInvoice | null> {
  if (!id) return null;
  const snap = await getDb().collection("salesPortalInvoices").doc(id).get();
  if (!snap.exists) return null;
  return serializeInvoice(snap.id, snap.data() || {});
}

export async function getInvoiceByNumber(numberRaw: string): Promise<PortalInvoice | null> {
  const number = String(numberRaw || "").trim().toUpperCase();
  if (!number) return null;
  const org = await getLuxesupplyOrg();
  const snap = await getDb()
    .collection("salesPortalInvoices")
    .where("organizationId", "==", org.id)
    .where("invoiceNumber", "==", number)
    .limit(1)
    .get();
  if (snap.empty) return null;
  const doc = snap.docs[0]!;
  return serializeInvoice(doc.id, doc.data() || {});
}

export async function updateInvoiceStatus(
  invoiceId: string,
  status: string,
  updatedBy: string,
): Promise<PortalInvoice> {
  const ref = getDb().collection("salesPortalInvoices").doc(invoiceId);
  const snap = await ref.get();
  if (!snap.exists) throw new Error("Invoice not found.");

  const payload: Record<string, unknown> = { status, updatedAt: new Date(), updatedBy };
  if (status === FIRESTORE_INVOICE_STATUS.PAID) payload.paidAt = new Date();
  await ref.update(payload);

  const next = await ref.get();
  return serializeInvoice(next.id, next.data() || {});
}

/**
 * Record a (possibly partial) payment against an invoice. When cumulative
 * payments reach the invoice total, the invoice flips to PAID (paidAt set) —
 * same end state as the mark-paid shortcut, which remains available for
 * one-step full payments.
 */
export async function recordInvoicePayment(
  invoiceId: string,
  payment: { amount: number; method?: string; reference?: string; note?: string },
  recordedBy: string,
): Promise<{ invoice: PortalInvoice; fullyPaid: boolean }> {
  const amount = Math.round(Number(payment.amount) * 100) / 100;
  if (!Number.isFinite(amount) || amount <= 0) throw new Error("Enter a payment amount above 0.");

  const ref = getDb().collection("salesPortalInvoices").doc(invoiceId);
  const snap = await ref.get();
  if (!snap.exists) throw new Error("Invoice not found.");
  const data = snap.data() || {};
  if (String(data.status || "") === FIRESTORE_INVOICE_STATUS.PAID) {
    throw new Error("Invoice is already paid in full.");
  }

  const existing = Array.isArray(data.payments) ? (data.payments as unknown[]) : [];
  const priorPaid = existing.reduce(
    (s: number, p) => s + (Number((p as Record<string, unknown>).amount) || 0),
    0,
  );
  const total = Number(data.total || 0);
  const nowPaid = priorPaid + amount;
  const fullyPaid = nowPaid >= total - 0.005;

  const entry = {
    amount,
    method: String(payment.method || "wire").slice(0, 40),
    reference: String(payment.reference || "").slice(0, 120),
    note: String(payment.note || "").slice(0, 500),
    receivedAt: new Date(),
    recordedBy,
  };
  const update: Record<string, unknown> = {
    payments: [...existing, entry],
    updatedAt: new Date(),
    updatedBy: recordedBy,
  };
  if (fullyPaid) {
    update.status = FIRESTORE_INVOICE_STATUS.PAID;
    update.paidAt = new Date();
  }
  await ref.update(update);

  const next = await ref.get();
  return { invoice: serializeInvoice(next.id, next.data() || {}), fullyPaid };
}

/** Stamp when an overdue reminder email went out (cron throttle). */
export async function markReminderSent(invoiceId: string): Promise<void> {
  await getDb()
    .collection("salesPortalInvoices")
    .doc(invoiceId)
    .update({ lastReminderAt: new Date() });
}

/** Minimal viable fulfillment: staff records carrier + tracking once the pieces ship. */
/** Seller → shipper note for this order; shown on the pack station. */
export async function setInvoicePackingNote(
  invoiceId: string,
  note: string,
  updatedBy: string,
): Promise<PortalInvoice> {
  const ref = getDb().collection("salesPortalInvoices").doc(invoiceId);
  const snap = await ref.get();
  if (!snap.exists) throw new Error("Invoice not found.");
  await ref.update({
    packingNote: String(note || "").trim().slice(0, 1000),
    updatedAt: new Date(),
    updatedBy,
  });
  const saved = await ref.get();
  return serializeInvoice(saved.id, saved.data() || {});
}

/**
 * Pay-first hold: packing is complete but the buyer's terms are "Due on
 * receipt" and the invoice isn't paid — the shipment waits as FULFILLED
 * until payment lands, then staff complete it again to ship.
 */
export async function markInvoiceFulfilled(
  invoiceId: string,
  updatedBy: string,
): Promise<PortalInvoice> {
  const ref = getDb().collection("salesPortalInvoices").doc(invoiceId);
  const snap = await ref.get();
  if (!snap.exists) throw new Error("Invoice not found.");
  if ((snap.data() || {}).fulfillmentStatus === FULFILLMENT_STATUS.SHIPPED) {
    throw new Error("This invoice has already shipped.");
  }

  await ref.update({
    fulfillmentStatus: FULFILLMENT_STATUS.FULFILLED,
    fulfilledAt: new Date(),
    updatedAt: new Date(),
    updatedBy,
  });

  const next = await ref.get();
  return serializeInvoice(next.id, next.data() || {});
}

export async function markInvoiceShipped(
  invoiceId: string,
  opts: { carrier: string; trackingNumber?: string },
  updatedBy: string,
): Promise<PortalInvoice> {
  const ref = getDb().collection("salesPortalInvoices").doc(invoiceId);
  const snap = await ref.get();
  if (!snap.exists) throw new Error("Invoice not found.");

  await ref.update({
    fulfillmentStatus: FULFILLMENT_STATUS.SHIPPED,
    carrier: opts.carrier,
    trackingNumber: opts.trackingNumber || null,
    shippedAt: new Date(),
    updatedAt: new Date(),
    updatedBy,
  });

  const next = await ref.get();
  return serializeInvoice(next.id, next.data() || {});
}

/** Admin undo of markInvoiceShipped — clears tracking and flips back to UNFULFILLED. */
export async function markInvoiceUnshipped(
  invoiceId: string,
  updatedBy: string,
): Promise<PortalInvoice> {
  const ref = getDb().collection("salesPortalInvoices").doc(invoiceId);
  const snap = await ref.get();
  if (!snap.exists) throw new Error("Invoice not found.");

  await ref.update({
    fulfillmentStatus: FULFILLMENT_STATUS.UNFULFILLED,
    carrier: null,
    trackingNumber: null,
    shippedAt: null,
    updatedAt: new Date(),
    updatedBy,
  });

  const next = await ref.get();
  return serializeInvoice(next.id, next.data() || {});
}
