import { getDb, toIso } from "./admin";
import { getLuxesupplyOrg } from "./staff";
import { getQuoteById, linkQuoteToInvoice, finalizeInvoiceRequestAsSold } from "./quotes";
import {
  FIRESTORE_INVOICE_STATUS,
  FULFILLMENT_STATUS,
  INVOICE_TERMS,
  type FulfillmentStatus,
} from "@/lib/constants";

// Formal invoices generated by staff from an approved/processed invoice
// request (`salesPortalQuotes`). Separate collection so the request pipeline
// (open → contacted → quoted) and the invoice/fulfillment lifecycle
// (SENT → PAID, UNFULFILLED → SHIPPED) don't overload one document shape.
export type InvoiceLineItem = {
  sku: string;
  title: string;
  brand: string;
  quantity: number;
  price: number;
  imageUrl: string | null;
};

export type PortalInvoice = {
  id: string;
  invoiceNumber: string;
  quoteId: string;
  organizationId: string;
  portalUsername: string;
  buyerDisplayName: string;
  customerName: string;
  customerEmail: string;
  customerCompany: string;
  customerPhone: string;
  items: InvoiceLineItem[];
  itemCount: number;
  subtotal: number;
  shipping: number;
  total: number;
  terms: string;
  poNumber: string | null;
  status: string;
  fulfillmentStatus: FulfillmentStatus;
  carrier: string | null;
  trackingNumber: string | null;
  shippedAt: string | null;
  issuedAt: string | null;
  dueDate: string | null;
  paidAt: string | null;
  createdAt: string | null;
  updatedAt: string | null;
  createdBy: string;
};

function serializeInvoice(id: string, d: Record<string, unknown>): PortalInvoice {
  const items = Array.isArray(d.items) ? (d.items as Array<Record<string, unknown>>) : [];
  return {
    id,
    invoiceNumber: String(d.invoiceNumber || ""),
    quoteId: String(d.quoteId || ""),
    organizationId: String(d.organizationId || ""),
    portalUsername: String(d.portalUsername || ""),
    buyerDisplayName: String(d.buyerDisplayName || ""),
    customerName: String(d.customerName || ""),
    customerEmail: String(d.customerEmail || ""),
    customerCompany: String(d.customerCompany || ""),
    customerPhone: String(d.customerPhone || ""),
    items: items.map((i) => ({
      sku: String(i.sku || ""),
      title: String(i.title || ""),
      brand: String(i.brand || ""),
      quantity: Math.max(1, Math.round(Number(i.quantity) || 1)),
      price: Number(i.price) || 0,
      imageUrl: i.imageUrl ? String(i.imageUrl) : null,
    })),
    itemCount: Number(d.itemCount || items.length || 0),
    subtotal: Number(d.subtotal || 0),
    shipping: Number(d.shipping || 0),
    total: Number(d.total || 0),
    terms: String(d.terms || INVOICE_TERMS),
    poNumber: d.poNumber ? String(d.poNumber) : null,
    status: String(d.status || FIRESTORE_INVOICE_STATUS.SENT),
    fulfillmentStatus: (String(d.fulfillmentStatus || FULFILLMENT_STATUS.UNFULFILLED) as FulfillmentStatus),
    carrier: d.carrier ? String(d.carrier) : null,
    trackingNumber: d.trackingNumber ? String(d.trackingNumber) : null,
    shippedAt: toIso(d.shippedAt),
    issuedAt: toIso(d.issuedAt),
    dueDate: toIso(d.dueDate),
    paidAt: toIso(d.paidAt),
    createdAt: toIso(d.createdAt),
    updatedAt: toIso(d.updatedAt),
    createdBy: String(d.createdBy || ""),
  };
}

/** Display status: OVERDUE is computed, never stored, so "mark paid" stays the only status mutation. */
export function displayInvoiceStatus(inv: { status: string; dueDate: string | null }): string {
  if (
    inv.status === FIRESTORE_INVOICE_STATUS.SENT &&
    inv.dueDate &&
    new Date(inv.dueDate).getTime() < Date.now()
  ) {
    return "OVERDUE";
  }
  return inv.status;
}

async function nextInvoiceNumber(orgId: string): Promise<string> {
  const db = getDb();
  const ref = db.collection("organizations").doc(orgId);
  const seq = await db.runTransaction(async (tx) => {
    const snap = await tx.get(ref);
    const data = (snap.data() || {}) as Record<string, unknown>;
    const salesPortal = (data.salesPortal || {}) as Record<string, unknown>;
    const current = Number(salesPortal.invoiceSeq) || 1000;
    const next = current + 1;
    tx.set(
      ref,
      { salesPortal: { ...salesPortal, invoiceSeq: next }, updatedAt: new Date() },
      { merge: true },
    );
    return next;
  });
  return `INV-${seq}`;
}

/**
 * Staff action: turn a priced invoice request into a formal invoice. Snapshots
 * the request's current line items/total, assigns a sequential invoice
 * number, and links the two documents both ways (invoice.quoteId,
 * quote.invoiceId) so either side can navigate to the other.
 */
export async function createInvoiceFromQuote(
  quoteId: string,
  staffEmail: string,
): Promise<PortalInvoice> {
  const quote = await getQuoteById(quoteId);
  if (!quote) throw new Error("Order request not found.");
  if (quote.invoiceId) throw new Error("This request already has an invoice.");
  if (!quote.items.length) throw new Error("Cannot invoice an empty request.");

  const org = await getLuxesupplyOrg();
  const invoiceNumber = await nextInvoiceNumber(org.id);
  const now = new Date();
  const dueDate = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

  const items: InvoiceLineItem[] = quote.items.map((i) => ({
    sku: String(i.sku || ""),
    title: String(i.title || ""),
    brand: String(i.brand || ""),
    quantity: Math.max(1, Math.round(Number(i.quantity) || 1)),
    price: Number(i.price) || 0,
    imageUrl: i.imageUrl ? String(i.imageUrl) : null,
  }));
  const subtotal =
    quote.cartTotal != null ? Math.round(quote.cartTotal) : items.reduce((s, i) => s + i.price * i.quantity, 0);
  const shipping = Math.max(0, Math.round(Number(quote.shipping) || 0));
  const total = subtotal + shipping;

  const ref = getDb().collection("salesPortalInvoices").doc();
  await ref.set({
    invoiceNumber,
    quoteId,
    organizationId: org.id,
    portalUsername: quote.portalUsername,
    buyerDisplayName: quote.buyerDisplayName,
    customerName: quote.customerName,
    customerEmail: quote.customerEmail,
    customerCompany: quote.customerCompany,
    customerPhone: quote.customerPhone,
    items,
    itemCount: items.length,
    subtotal,
    shipping,
    total,
    terms: INVOICE_TERMS,
    poNumber: null,
    status: FIRESTORE_INVOICE_STATUS.SENT,
    fulfillmentStatus: FULFILLMENT_STATUS.UNFULFILLED,
    carrier: null,
    trackingNumber: null,
    shippedAt: null,
    issuedAt: now,
    dueDate,
    paidAt: null,
    createdAt: now,
    updatedAt: now,
    createdBy: staffEmail,
  });

  await linkQuoteToInvoice(quoteId, { id: ref.id, invoiceNumber });
  await finalizeInvoiceRequestAsSold(quoteId, staffEmail);

  const saved = await ref.get();
  return serializeInvoice(saved.id, saved.data() || {});
}

export async function listInvoices(opts?: { limit?: number }): Promise<PortalInvoice[]> {
  const org = await getLuxesupplyOrg();
  const limitCount = Math.min(Math.max(opts?.limit || 100, 1), 300);
  const db = getDb();

  let snap;
  try {
    snap = await db
      .collection("salesPortalInvoices")
      .where("organizationId", "==", org.id)
      .orderBy("createdAt", "desc")
      .limit(limitCount)
      .get();
  } catch {
    snap = await db
      .collection("salesPortalInvoices")
      .where("organizationId", "==", org.id)
      .limit(limitCount)
      .get();
  }

  return snap.docs
    .map((doc) => serializeInvoice(doc.id, doc.data() || {}))
    .sort((a, b) => String(b.createdAt || "").localeCompare(String(a.createdAt || "")));
}

export async function listInvoicesForBuyer(username: string): Promise<PortalInvoice[]> {
  if (!username) return [];
  const org = await getLuxesupplyOrg();
  const db = getDb();

  let snap;
  try {
    snap = await db
      .collection("salesPortalInvoices")
      .where("organizationId", "==", org.id)
      .where("portalUsername", "==", username)
      .orderBy("createdAt", "desc")
      .limit(100)
      .get();
  } catch {
    snap = await db
      .collection("salesPortalInvoices")
      .where("organizationId", "==", org.id)
      .where("portalUsername", "==", username)
      .limit(100)
      .get();
  }

  return snap.docs
    .map((doc) => serializeInvoice(doc.id, doc.data() || {}))
    .sort((a, b) => String(b.createdAt || "").localeCompare(String(a.createdAt || "")));
}

export async function getInvoiceById(id: string): Promise<PortalInvoice | null> {
  if (!id) return null;
  const snap = await getDb().collection("salesPortalInvoices").doc(id).get();
  if (!snap.exists) return null;
  return serializeInvoice(snap.id, snap.data() || {});
}

export async function getInvoiceByNumber(numberRaw: string): Promise<PortalInvoice | null> {
  const number = String(numberRaw || "").trim().toUpperCase();
  if (!number) return null;
  const org = await getLuxesupplyOrg();
  const snap = await getDb()
    .collection("salesPortalInvoices")
    .where("organizationId", "==", org.id)
    .where("invoiceNumber", "==", number)
    .limit(1)
    .get();
  if (snap.empty) return null;
  const doc = snap.docs[0]!;
  return serializeInvoice(doc.id, doc.data() || {});
}

export async function updateInvoiceStatus(
  invoiceId: string,
  status: string,
  updatedBy: string,
): Promise<PortalInvoice> {
  const ref = getDb().collection("salesPortalInvoices").doc(invoiceId);
  const snap = await ref.get();
  if (!snap.exists) throw new Error("Invoice not found.");

  const payload: Record<string, unknown> = { status, updatedAt: new Date(), updatedBy };
  if (status === FIRESTORE_INVOICE_STATUS.PAID) payload.paidAt = new Date();
  await ref.update(payload);

  const next = await ref.get();
  return serializeInvoice(next.id, next.data() || {});
}

/** Minimal viable fulfillment: staff records carrier + tracking once the pieces ship. */
export async function markInvoiceShipped(
  invoiceId: string,
  opts: { carrier: string; trackingNumber?: string },
  updatedBy: string,
): Promise<PortalInvoice> {
  const ref = getDb().collection("salesPortalInvoices").doc(invoiceId);
  const snap = await ref.get();
  if (!snap.exists) throw new Error("Invoice not found.");

  await ref.update({
    fulfillmentStatus: FULFILLMENT_STATUS.SHIPPED,
    carrier: opts.carrier,
    trackingNumber: opts.trackingNumber || null,
    shippedAt: new Date(),
    updatedAt: new Date(),
    updatedBy,
  });

  const next = await ref.get();
  return serializeInvoice(next.id, next.data() || {});
}
