import Link from "next/link";
import { redirect } from "next/navigation";
import { getSession } from "@/lib/auth";
import { ROLE } from "@/lib/constants";
import { listInvoicesForBuyer, displayInvoiceStatus } from "@/lib/firestore/invoices";
import { EmptyState } from "@/components/EmptyState";
import { InvoiceBadge, FulfillmentBadge } from "@/components/badges";
import { money, fullDate } from "@/lib/format";

export const dynamic = "force-dynamic";

export default async function BuyerInvoicesPage() {
  const session = await getSession();
  if (!session || session.role !== ROLE.BUYER) redirect("/wholesale/sign-in");

  const invoices = session.username ? await listInvoicesForBuyer(session.username) : [];

  return (
    <div className="px-8 pb-16 pt-8">
      <h1 className="text-[24px] font-semibold text-ink">Invoices</h1>
      <p className="mt-1 text-[13px] text-secondary">
        Formal Net-30 invoices generated by our team once an order request is processed.
      </p>

      {invoices.length === 0 ? (
        <EmptyState
          title="No invoices yet."
          hint="Once the sales team processes your order request, the formal invoice will appear here."
          className="mt-8"
        />
      ) : (
        <div className="mt-8 overflow-hidden rounded-card border border-border bg-surface">
          <div className="grid grid-cols-[110px_1fr_90px_100px_110px_120px] gap-x-4 border-b border-border px-5 py-3 font-mono text-[10px] uppercase tracking-[0.12em] text-muted">
            <span>Invoice</span>
            <span>Issued</span>
            <span className="text-center">Items</span>
            <span className="text-right">Total</span>
            <span className="text-center">Status</span>
            <span className="text-center">Fulfillment</span>
          </div>
          {invoices.map((inv) => (
            <Link
              key={inv.id}
              href={`/wholesale/invoices/${inv.invoiceNumber}`}
              className="grid grid-cols-[110px_1fr_90px_100px_110px_120px] gap-x-4 items-center border-b border-border/60 px-5 py-3.5 text-[12.5px] text-[#3A3934] last:border-b-0 hover:bg-ground"
            >
              <span className="font-mono">{inv.invoiceNumber}</span>
              <span className="font-mono text-[11px] text-muted">{fullDate(inv.issuedAt)}</span>
              <span className="text-center font-mono">{inv.itemCount}</span>
              <span className="text-right font-mono">{money(inv.total)}</span>
              <span className="text-center">
                <InvoiceBadge status={displayInvoiceStatus(inv)} />
              </span>
              <span className="text-center">
                <FulfillmentBadge status={inv.fulfillmentStatus} />
              </span>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}
